services:
  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-notes}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - notes_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:8.2-alpine
    container_name: laravel_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis:/usr/local/etc/redis
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - notes_app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Main Project on Laravel
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "5173:5173" # Port for Vite (npm / bootstrap)
    volumes:
      - ./:/var/www
      - vendor_volume:/var/www/vendor
      - node_modules_volume:/var/www/node_modules
    environment:
      # PostgreSQL variables
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-notes}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-secret}

      # Redis variables
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - notes_app

  # Nginx веб-сервер
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - notes_app

networks:
  notes_app:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  vendor_volume:
  node_modules_volume:
